### PR TITLE
fix CUDA PMR Allocator Compilation Error

### PR DESCRIPTION
**Pull request by FantasyVR**
I'm encountering build errors with libupic. The core issue appears to be an incompatibility between std::pmr::polymorphic_allocator and the CUDA construction of ulonglong2. Specifically, the allocator is not compatible with how ulonglong2 is being created within the CUDA compilation process. It can be fixed with POD structs data type as shown in my PR.

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.348
08\include\xpolymorphic_allocator.h(285): error : expected an expression [F:\libuipc\build\src\backends\cuda\cuda.vcxproj]
_Uty(::std:: forward<decltype(_Construct_args)>(_Construct_args)...); 
detected during instantiation of "void std::pmr::polymorphic_allocator<_Ty>::construct(_Uty *, _Types &&...)
 [with _Ty=uipc::backend::cuda::SizeT2, _Uty=uipc::backend::cuda::SizeT2, _Types=<>]" at line 619 of 
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\xmemory



C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\xpolymorphic_allocator.h(285): error : expected an expression [F:\libuipc\build\src\backends\cuda\cuda.vcxproj]
_Uty(::std:: forward<decltype(_Construct_args)>(_Construct_args)...);
detected during instantiation of "void std::pmr::polymorphic_allocator<_Ty>::construct(_Uty *, _Types &&...) [with _Ty=uipc::backend::cuda::Size T2, _Uty=uipc::backend::cuda::SizeT2, _Types=<>]" at line 619 of C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\xmemory

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\xpolymorphic_allocator.h(285): error : expected a ")" [F:\libuipc\build\src\backends\cuda\cuda.vcxproj]
_Uty(::std:: forward<decltype(_Construct_args)>(_Construct_args)...);
detected during instantiation of "void std::pmr::polymorphic_allocator<_Ty>::construct(_Uty *, _Types &&...) [with _Ty=uipc::backend::cuda::Size T2, _Uty=uipc::backend::cuda::SizeT2, _Types=<>]" at line 619 of C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\xmemory
```

### CODE REVIEW

**Comment by MuGdxy** [comment]
Yes! I think it's a good workaround for this NVCC-specific compile problem. I guess the MSVC and NVCC have some conflicts in certain newer versions.

**Comment by FantasyVR** [comment]
> Hi Peng Yu, thanks for your help. May I ask which cuda version you are using

Hi Kemeng, I'm currently working with CUDA 12.8 and Visual Studio 2022.
```
C:\Users\Peng>nvidia-smi
Tue Sep  9 11:57:34 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.83                 Driver Version: 572.83         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   44C    P8             11W /  170W |    1802MiB /  12288MiB |     20%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```
